### ISSUE TITLE
Random test failures

### ISSUE THREAD

**Issue by eserte** [srchulo/Mojolicious-Plugin-Gzip#1]
The test suite randomly fails, see http://fast-matrix.cpantesters.org/?dist=Mojolicious-Plugin-Gzip%200.02
Mostly it's t/etag.t failing, but sometimes also t/minsize.t or t/basic.t.

**Comment by srchulo** [comment]
Thanks for letting me know! Fixed here:

https://github.com/srchulo/Mojolicious-Plugin-Gzip/commit/255c8d4309f50b21184d349ffba54a7f8d33775a
https://metacpan.org/release/SRCHULO/Mojolicious-Plugin-Gzip-0.03
